# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171207_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkroom',
            name='user',
        ),
        migrations.AddField(
            model_name='time',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='app01.User', verbose_name='预定用户'),
        ),
    ]
