# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171207_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='title',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='time',
            name='date',
        ),
        migrations.RemoveField(
            model_name='time',
            name='user',
        ),
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.CharField(default=1, max_length=32, verbose_name='开会时间小时表示'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='user',
            field=models.ManyToManyField(related_name='user_date', to='app01.User', verbose_name='预定用户'),
        ),
        migrations.AlterField(
            model_name='date',
            name='talkroom',
            field=models.ManyToManyField(related_name='date_talkroom', to='app01.TalkRoom', verbose_name='预定会议室'),
        ),
    ]
